apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../k8s
  - ../../k8s/optional-http

images:
  - name: ghcr.io/erauner/investigation-poc
    newName: investigation-poc
    newTag: local

patches:
  - path: patch-mcp-deployment.yaml
  - path: patch-http-deployment.yaml
