apiVersion: apps/v1
kind: Deployment
metadata:
  name: investigation-service
  namespace: kagent
spec:
  template:
    spec:
      containers:
        - name: api
          imagePullPolicy: IfNotPresent
