apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../k8s
  - prometheus-gateway.yaml

images:
  - name: ghcr.io/erauner/investigation-poc
    newName: investigation-poc
    newTag: local

patches:
  - path: patch-configmap.yaml
  - path: patch-cluster-registry-configmap.yaml
  - path: patch-mcp-deployment.yaml
