apiVersion: v1
kind: Service
metadata:
  name: prometheus-gateway
  namespace: kagent
spec:
  type: ExternalName
  externalName: host.docker.internal
  ports:
    - name: http
      port: 9090
      targetPort: 9090
