apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - alertmanager-remotemcpserver.yaml
  - alertmanager-mcp-serviceaccount.yaml
  - alertmanager-mcp-deployment.yaml
  - alertmanager-mcp-service.yaml
